Update needed for Rust v1.77.1
error: file opened with `create`, but `truncate` behavior not defined
   --> packages/modules/Virtualization/authfs/tests/common/src/open_then_run.rs:120:18
    |
120 |                 .create(true)
    |                  ^^^^^^^^^^^^- help: add: `.truncate(true)`
    |
    = help: if you intend to overwrite an existing file entirely, call `.truncate(true)`
    = help: if you instead know that you may want to keep some parts of the old file, call `.truncate(false)`
    = help: alternatively, use `.append(true)` to append to the file instead of overwriting it
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#suspicious_open_options
    = note: `-D clippy::suspicious-open-options` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::suspicious_open_options)]`



Bug: 330185853
 ./test_compiler.py --prebuilt-path dist/rust-dev.tar.xz  --target aosp_cf_x86_64_phone --image

Test: m rust
Change-Id: Ia36fc8087f59ee15a3a481e1ce0f7eb6225a6e30